[package]
name = "kg-diag"
version = "0.1.0"
authors = ["Jakub Chłapiński <jakub.chlapinski@kodegenix.pl>"]
description = """
Error/diagnostic management
"""
readme = "README.md"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/Kodegenix/kg-diag"
workspace = ".."

[dependencies]
kg-display-derive = "0.1"
backtrace = "0.3"

[dev-dependencies]
kg-io = "0.1"

